spring:
  h2:
    console:
      enabled: true
#  datasource:
#    url: jdbc:h2:mem:testdb;MODE=mysql
#    username: sa
#    driver-class-name: org.h2.Driver
  datasource:
    url: jdbc:mysql://localhost:3306/testdb
    username: root


